apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpecho
  name: httpecho-svc
spec:
  ports:
  - name: 5678-5678
    port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: httpecho
  type: ClusterIP
status:
  loadBalancer: {}