apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpecho
  name: httpecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpecho
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpecho
    spec:
      containers:
      - image: hashicorp/http-echo
        args: ["-text", "Hello Sapient Logic"]
        name: http-echo
        ports:
        - containerPort: 5678
        resources: {}
status: {}