apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: synapse
  POSTGRES_USER: postgres
  POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF-8"